Добавляет разметку главной и внутренней страницы
htmlacademy-htmlcss/1737917-device-36 pull request #2
Opened 2023-02-09 14:26 UTC by Bezlpetr

2023-02-12 13:59 UTC, andreysgra requested changes
Несмотря на замечания в целом задание выполнено правильно.

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +          <input class="navigation-search-form-input" type="text" id="navigation-search-form-input"
Лучше использовать `type=search`, так как это поле поиска.

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +            <button class="navigation-user-button-logout" type="button">Выйти</button>
Хотелось бы понять почему:
1. Имя пользователя просто текст, а не ссылка на профиль.
2. Почему элемент "выйти" кнопка, а не ссылка.

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +            <button class="navigation-user-button-login" type="button">Войти</button>
Здесь тоже интересно узнать, почему здесь кнопка, а не ссылка.

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +            <button class="navigation-item-button-catalog" type="button">Каталог товаров</button>
Почему не ссылка? Ведь ссылка может быть на страницу каталога, где представлены все разделы каталога.

Дело в том, что `button` без JS не имеет встроенной функциональности и соответственно потеряется часть интерактивности сайта, чего не скажешь о ссылке.

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +        <h2 class="sorting-title">Сортировка:</h2>
А может это просто текст, а не заголовок?

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +            <a class="button product-card-button" href="#">
К чему в этой ссылке класс `button`? Обычно в этом классе описывают свойства типичной кнопки (ссылки, выглядящей как кнопка) для всего сайта. В данном макете в этот класс можно выделить такие элементы, как "показать", "подробнее о нас" и так далее.

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +              <span class="product-card-new product-card-new-visible">new</span>
Можно использовать псевдо элемент `::before`.

2023-02-12 13:59 UTC, andreysgra commented on catalog.html
> +              <span class="product-card-button-label">Подробнее</span>
Однозначно ссылка на соответствующую страницу товара, но никак не `span`.

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +        <a class="logo-link logo-header" href="#">
В `href` либо ссылка на главную страницу, либо чтобы ссылка не была интерактивной вообще без атрибута `href`.

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +            <button class="navigation-user-button-logout" type="button">Выйти</button>
Ссылки, в не кнопки.

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +            <button class="navigation-item-button-catalog" type="button">Каталог товаров</button>
Ссылка.

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +      <a href="https://oprosso.net/p/MAhGrMHxDkvEbbpJy">Опроссо</a>
?

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +            </button>
Этот блок для переключения слайдов должен быть один на все слайды, а не для каждого слайда отдельно. Его нужно вынести на уровень `promo-slider`.

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +      <button class="delivery-order-button" type="button">Доставим редкий товар под заказ</button>
На мой взгляд - ссылка. Ссылка предполагает переход на страницу сайта, а кнопка без кода JS (если это не `submit`) ничего не делает.

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +            <label for="subscribe-email"></label>
Стоит добавить поясняющий текст в `label`, а сам тег доступно скрыть.

2023-02-12 13:59 UTC, andreysgra commented on index.html
> +      <a class="logo-link logo-footer" href="#">
Аналогично замечанию верхнего логотипа сайта.

2023-02-12 20:29 UTC, Bezlpetr commented on catalog.html
> +          <input class="navigation-search-form-input" type="text" id="navigation-search-form-input"
исправил на index.html и catalog.html

2023-02-12 20:46 UTC, Bezlpetr commented on catalog.html
> +            <button class="navigation-user-button-logout" type="button">Выйти</button>
1. Имя пользователя сделал ссылкой
2. На мой взгляд, при нажатии на кнопку выйти должен отрабатывать скрипт, который ряд элементов скрывает, разве не так? Ссылка куда будет вести? или у нас будет две страницы index.html, одна для авторизованного пользователя, а вторая для неавторизованного пользователя? не очень понимаю, но переделал на ссылку кнопки "Войти" и "Выйти". Буду благодарен за разъяснение этого момента.

2023-02-12 20:46 UTC, Bezlpetr commented on catalog.html
> +            <button class="navigation-user-button-login" type="button">Войти</button>
Исправил. Мой комментарий выше

2023-02-12 20:54 UTC, Bezlpetr commented on catalog.html
> +            <button class="navigation-item-button-catalog" type="button">Каталог товаров</button>
Я правильно понял, что для надежности делают страницу с каталогом и ссылку на нее, дополнительно навешивают Javascript для красивого выпадающего меню? Правда, до конца не понял как это фактически делается. Можете пояснить чуть больше. Я исправил.

2023-02-12 20:59 UTC, Bezlpetr commented on catalog.html
> +        <h2 class="sorting-title">Сортировка:</h2>
Если я правильно сделал, когда выделил элементы для сортировки товаров в section, то тогда надо задать заголовок для данной секции. На мой взгляд, "Сортировка:" отражает содержание секции. Если я заменю на текст, то добавлю скрытый заголовок "Сортировка", на сколько это правильно?

2023-02-12 21:01 UTC, Bezlpetr commented on index.html
> +      <a href="https://oprosso.net/p/MAhGrMHxDkvEbbpJy">Опроссо</a>
Да, это я добавил попробовать, как будет отображаться на сайте, и не удалил. Мой косяк. Исправил

2023-02-12 21:04 UTC, Bezlpetr commented on index.html
> +            </button>
Были такие мысли, но остановился на реализации, когда все кнопки повторяются. Исправил.

2023-02-12 21:07 UTC, Bezlpetr commented on index.html
> +      <button class="delivery-order-button" type="button">Доставим редкий товар под заказ</button>
Исправил.

2023-02-12 21:11 UTC, Bezlpetr commented on index.html
> +            <label for="subscribe-email"></label>
Добавил.

2023-02-12 21:22 UTC, Bezlpetr commented on catalog.html
> +            <a class="button product-card-button" href="#">
Да, перестарался:) Удалил

2023-02-12 21:23 UTC, Bezlpetr commented on catalog.html
> +              <span class="product-card-new product-card-new-visible">new</span>
Можно и так, давайте пока удалю.

2023-02-12 21:32 UTC, Bezlpetr commented on catalog.html
> +              <span class="product-card-button-label">Подробнее</span>
Здесь я возможно понял неверно. Я думал, что, так как в стайлгайде карточка вся изменяется при наведении и нажатии, то я ее сделал ссылкой целиком и поэтому отдельно "Подробнее" делать ссылкой нет смысла. Или ее не надо  делать ссылкой, а надо только показать кнопку "Подробнее" при наведении? Давайте, если я не прав, то поправлю в следующий раз

2023-02-12 21:33 UTC, Bezlpetr commented on index.html
> +        <a class="logo-link logo-header" href="#">
Исправил

2023-02-12 21:34 UTC, Bezlpetr commented on index.html
> +            <button class="navigation-user-button-logout" type="button">Выйти</button>
Исправил

2023-02-12 21:35 UTC, Bezlpetr commented on index.html
> +            <button class="navigation-item-button-catalog" type="button">Каталог товаров</button>
Исправил

2023-02-12 21:35 UTC, Bezlpetr commented on index.html
> +      <a class="logo-link logo-footer" href="#">
Исправил

2023-02-12 21:46 UTC, Bezlpetr commented
Я немного отстаю и поэтому тороплюсь. Пока разбирался положен ли мне наставник или нет, пока пулреквест был на проверке, я двигался дальше, поэтому сделано уже следующее задание и начата стилизация.

2023-02-13 08:18 UTC, andreysgra commented on catalog.html
> +            <button class="navigation-user-button-logout" type="button">Выйти</button>
По поводу элемента "выйти". С одной стороны ваши рассуждения логичны, что этот элемент можно разметить кнопкой и есть немало примеров, где так и поступают. Практически все современные сайты не могут полноценно работать без JS. Но если мы хотим, чтобы в отсутствии JS (причины на это могут быть разными) критическая функциональность сайта осталась, то мы должны позаботиться об этом. В данном случае ссылка "выйти" может содержать GET параметры (что-то вроде `?user&logout`), которые передадут серверу информацию о том, что нужно отключить пользователя. Сервер вернёт браузеру код страницы сайта уже неавторизованного пользователя и собственно перехода на специальную страницу неавторизованного пользователя нет.

Обычно такие моменты описываются в ТЗ, но в данном случае нам приходится самостоятельно решать вопрос. Кнопка без JS мертва, а вот ссылка с GET параметром позволит произвести нужные действия. Я не настаиваю на том, что обязательно нужно использовать ссылку - хотите, пусть будет кнопка.

2023-02-13 08:24 UTC, andreysgra commented on catalog.html
> +            <button class="navigation-item-button-catalog" type="button">Каталог товаров</button>
Правильно поняли. Но в действительности делают по разному. Лучше использовать ссылку, чтобы сохранить критическую функциональность сайта.

Пример: 
а) элементы переключения слайдов размечены кнопками и при отсутствии JS слайды будет невозможно переключить. Потеряется ли критическая функциональность сайта? Нет. Ну не переключим слайды, ничего страшного;
б) элемент интерфейса "каталог" мы разметили кнопкой, а не ссылкой и если нет JS, то мы не можем попасть в разделы каталога. Теряется при этом критическая функциональность сайта? Да.

2023-02-13 08:27 UTC, andreysgra commented on catalog.html
> +        <h2 class="sorting-title">Сортировка:</h2>
Ну в принципе можно оставить, как есть. Не обратил внимание, что у вас там секция. Честно говоря засилье секций в проектах студентов довольно критическое 😄. Не то чтобы не стоит вообще использовать этот тег, не стоит использовать его так часто. На мой взгляд в секцию можно выделить довольно крупный раздел сайта.

2023-02-13 08:33 UTC, andreysgra commented on catalog.html
> +              <span class="product-card-button-label">Подробнее</span>
Давайте в следующий раз исправите.

Лично я думаю, что если есть элемент интерфейса "подробнее", который появляется при наведении курсора на карточку товара, то это ссылка, которая ведёт на соответствующую страницу. Иначе зачем этот элемент нужен? В то же время, если всю карточку товара делать ссылкой, то ссылка в ссылке не нужна, да и если не ошибаюсь, это будет ошибкой разметки. В макете есть стили при наведении на карточку и можно подумать, что это интерактивный элемент - ссылка, но вот "**подробнее**" говорит о другом. Думаю, что это просто эффект наведения и не более того.

2023-02-13 08:52 UTC, andreysgra approved these changes

2023-02-13 08:52 UTC, andreysgra commented on styles/styles.css
> +  max-width: 1160px;
Почему `max-width`? Эта вёрстка не адаптивная, поэтому ширину контентной области мы задаём фиксированным значением `width: 1160px`. А вот тегу `body` нужно задать минимальную ширину, равную ширину контентной области `min-width: 1160px` .

2023-02-13 08:52 UTC, andreysgra commented on styles/styles.css
> +  max-width: 1160px;
Здесь тоже самое.

2023-02-13 08:52 UTC, andreysgra commented on styles/styles.css
> +  max-width: 1160px;
И здесь тоже.

Вообще, можно все необходимы свойства контейнера контентной области вынести в один класс (у вас для этого есть класс `.container`) и применять этот класс к тем блокам, где нужно центрировать контент. А дополнительные свойства, специфичные для этого блока будут в своём классе.
```html
<ul class="catalog-navigation-list container">
  ***
</ul>
```
```css
.container {
  width: 1160px;
  margin: 0 auto;
}

.catalog-navigation-list {
  list-style: none;
}
```

2023-02-14 05:02 UTC, Bezlpetr commented on catalog.html
> +            <button class="navigation-user-button-logout" type="button">Выйти</button>
В целом понятно, не ясен один момент. "...Сервер вернёт браузеру код страницы сайта уже неавторизованного пользователя и собственно перехода на специальную страницу неавторизованного пользователя нет." - это что за код и если перехода на другую страницу не будет, то что будет?

2023-02-14 05:03 UTC, Bezlpetr commented on catalog.html
> +            <button class="navigation-item-button-catalog" type="button">Каталог товаров</button>
ясно

2023-02-14 05:38 UTC, Bezlpetr commented on catalog.html
> +        <h2 class="sorting-title">Сортировка:</h2>
Я решил переделать. Тем более, что в презентации html academy тоже почти вся страница каталога - это один section.

2023-02-14 05:43 UTC, Bezlpetr commented on styles/styles.css
> +  max-width: 1160px;
Ширину контентной области min-width: 1160px мы задаем, чтобы при недостаточности контента на странице она не становилась меньше?

2023-02-14 05:47 UTC, Bezlpetr commented on styles/styles.css
> +  max-width: 1160px;
исправил

2023-02-14 05:47 UTC, Bezlpetr commented on styles/styles.css
> +  max-width: 1160px;
Исправил

2023-02-14 07:14 UTC, andreysgra commented on catalog.html
> +            <button class="navigation-user-button-logout" type="button">Выйти</button>
То, что я описал выше, это общее определение, без конкретики, так как реализации многообразны.

Рассмотрим упрощённо взаимодействие браузера с сервером. Например у нас есть ссылка на страницу каталога. Когда пользователь нажимает на эту ссылку браузер посылает серверу запрос на получение ресурса catalog.html. Сервер ищет у себя такой ресурс и при успехе возвращает браузеру HTML код страницы. Тоже самое произойдёт, если браузер запросит у сервера ресурс **index.html?user&logout**. Сервер обработает параметры запроса и вернёт браузеру код главной страницы неавторизованного пользователя.

Немного иначе происходит взаимодействие браузера и сервера если действие пользователя обрабатываются на стороне клиента (браузера). При клике на ссылку код написанный с помощью JS сначала отменяет встроенный функционал ссылки, затем посылается запрос серверу для получения каких-то данных. Происходит обмен данными и сервер возвращает уже не HTML код страницы, а какие-то параметры на основании которых браузер вносит изменения в HTML страницу опять же при помощи кода JS.

2023-02-14 07:16 UTC, andreysgra commented on styles/styles.css
> +  max-width: 1160px;
Всё верно.

2023-02-14 07:17 UTC, andreysgra approved these changes

2023-02-14 07:17 UTC, merged