Добавляет мелкие сетки на гридах
htmlacademy-htmlcss/1737917-device-36 pull request #6
Opened 2023-02-27 06:02 UTC by Bezlpetr

2023-02-27 10:29 UTC, andreysgra requested changes
Нужно сделать перенос строк во флекс-контейнере, иначе при добавлении новых элементов списка получается вот так:
![image](https://user-images.githubusercontent.com/17790771/221536035-605b2692-523b-431d-a0c3-10c1d75d2571.png)

2023-02-27 10:29 UTC, andreysgra commented on styles/styles.css
> +  z-index: -1;
Решение с абсолютно позиционированным блоком слайдов крайне неудачное. Это не мелкий декоративный блок, где допускается такое позиционирование, а довольно крупный. У нас сейчас такого критерия нет, что нельзя использовать абсолютное позиционирование для крупных блоков, но тем не менее такой подход не приветствуется.

Здесь лучше пересмотреть подход к вёрстке и глянуть в сторону линейных градиентов. Можно выделить два основных блока:
![image](https://user-images.githubusercontent.com/17790771/221533248-938099d5-85e1-43ad-bed8-851faf8001f2.png)
1. Это шапка сайта, header.
2. Блок слайдов, секция `promo-slider`.

Шапке сайта зададим градиентную заливку **белый - жёлтый**, а секции слайдов тоже градиентную заливку, но в другом порядке **жёлтый - белый**.

При таком подходе не понадобится позиционирование, блок слайдов будет в потоке и идти сразу же после шапки сайта. Кроме того вы решите вопрос с дополнительными классами шапки `page-header-index`, `page-header-inner` которые станут просто не нужны.

Хотя в целом у вас и есть реализация фона через линейные градиенты, поэтому не вполне понятно, зачем вы стали использовать абсолютное позиционирование.

На всякий случай, если не будет получаться, то похожий пример реализации можно посмотреть [здесь](https://andreysgra.github.io/device/), но лучше сначала попробовать решить вопрос самостоятельно.

2023-02-27 10:29 UTC, andreysgra commented on styles/styles.css
> +  column-gap: 40px;
Намного логичнее, если все эти `grid` свойства будут у класса `promo-slider-item`, а класс `promo-slider-item-current` будет иметь только одно свойство - `display: grid` (так как `promo-slider-item` по умолчанию скрыт, то у него `display: none`).

2023-02-27 10:29 UTC, andreysgra commented on styles/styles.css
> +  margin: -29px 15px 29px 0;
> В качестве рекомендации, а не замечания.

Лично я не сторонник использования отрицательных значений у свойства `margin`. Чаще всего это следствие того, что верстальщик не смог правильно расположить элементы и нестыковки он подгоняет с помощью таких значений.

Здесь можно обойтись без "отрицательных марджинов", если нумерацию слайдов реализовать через абсолютно позиционированный псевдо элемент. Если в нём подключить счётчик `counter` то мы вообще нумерацию не будем проставлять вручную (пример в той же вёрстке по ссылке).

2023-02-28 14:15 UTC, Bezlpetr commented on styles/styles.css
> +  column-gap: 40px;
исправил

2023-02-28 20:36 UTC, Bezlpetr commented on styles/styles.css
> +  z-index: -1;
Я поправил. Счетчик применить не удалось, т.к. он не считает элементы, которые display:none, а visibility не освобождает место, надо по-хитрому скрывать, что-то типа visually-hidden. Не стал дальше копать, но зато познакомился с  счетчиками. 
У меня есть один вопрос. Можно ли заголовок  <h3> переместить после <img>? На сколько это правильно? С точки зрения семантики - это вроде неверно, заголовок должен быть первым в блоке, а с точки зрения удобства стилизации я бы <h3> перенес внутрь <div class="promo-slider-wrapper">, получился бы простой грид из двух колонок, а так я должен выделить ячейку для заголовка.
<li class="promo-slider-item ">
            <h3 class="title promo-slider-title">Худеем<br>правильно!</h3>
            <img class="promo-slider-image" src="images/slider/slider-2.png" width="560" height="560"
              alt="Фитнес-браслет.">
            <div class="promo-slider-wrapper">
              <p class="promo-slider-description">
                Мотивирующие фитнес-браслеты помогут найти в себе силы не
                пропускать занятия и соблюдать диету.
              </p>
              <a class="button promo-slider-link" href="#">Подробнее</a>
              <dl class="promo-slider-advantages">
                <div class="promo-slider-advantages-wrapper">
                  <dt class="promo-slider-advantages-item">Без подзарядки</dt>
                  <dd class="promo-slider-advantages-description">48 часов</dd>
                </div>
              </dl>
            </div>
          </li>

2023-02-28 20:45 UTC, Bezlpetr commented on styles/styles.css
> +  margin: -29px 15px 29px 0;
Исправил. Счетчик применить не удалось, т.к. он не считает элементы, которые display:none, а visibility не освобождает место, надо по-хитрому скрывать, что-то типа visually-hidden. Не стал дальше копать, но зато познакомился с  счетчиками.

2023-03-01 15:14 UTC, andreysgra commented on styles/styles.css
> +  z-index: -1;
Пожалуй не стоит ставить заголовок после изображения, если мы собираемся строго следовать семантике. Но выход, на мой взгляд, есть.

Посмотрим на текст "Делай селфи, как Бен Стиллер!". Он не очень то сильно похож на заголовок, так как этот текст не является названием товара, это некий призыв к действию, поэтому его лучше разметить тегом `p`. А самом начале слайда `promo-slider-item` можно поместить скрытый заголовок, текст которого будет описывать товар.

2023-03-01 15:20 UTC, andreysgra commented on styles/styles.css
> +  margin: -29px 15px 29px 0;
Здесь `visibility: hidden` очень даже можно использовать, если список `promo-slider-list` сделать `grid` контейнером. Ведь в `grid` поддерживает многослойность и один слайд будет находиться под другим. Посмотрите ещё раз мой пример, там как раз это задействовано. Кроме того, если бы я там не использовал свойство `visibility` не удалось бы сделать анимацию плавного перехода одного слайда в другой.

2023-03-01 15:21 UTC, merged

2023-03-01 18:30 UTC, Bezlpetr commented on styles/styles.css
> +  z-index: -1;
Переделал.

2023-03-01 19:42 UTC, Bezlpetr commented on styles/styles.css
> +  margin: -29px 15px 29px 0;
Спасибо! Переделал