Добавляет верстку оставшихся компонентов
htmlacademy-htmlcss/1737917-device-36 pull request #8
Opened 2023-03-12 16:03 UTC by Bezlpetr

2023-03-12 18:17 UTC, andreysgra requested changes
Использован не тот шрифт:
![image](https://user-images.githubusercontent.com/17790771/224564130-6c2bf297-030e-4a8b-bf1f-f4b6c6de8b43.png)
Заметно даже визуально:
![image](https://user-images.githubusercontent.com/17790771/224564147-c406dbf3-a6bc-4c31-86b7-3e5f59d0f836.png)

---

Если поле находится в фокусе, то оно почему-то поверх остального контента:
![image](https://user-images.githubusercontent.com/17790771/224564266-5419e1e9-a196-4d6b-98c9-5beea8e22a47.png)

2023-03-12 18:17 UTC, andreysgra commented on catalog.html
> +                    <button class="range-toggle toggle-max">
Нужно указать тип кнопки. [HTML-03](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-03).

2023-03-12 18:17 UTC, andreysgra commented on index.html
> +        <button class="modal-close-button">
Нужно указать тип кнопки. [HTML-03](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-03).

2023-03-12 18:17 UTC, andreysgra commented on index.html
> +                id="delivery-order-name" name="delivery-order-name" placeholder="Введите имя">
Поле обязательное для заполнения. [HTML-04](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-04).

2023-03-12 18:17 UTC, andreysgra commented on index.html
> +                id="delivery-order-email" name="delivery-order-email" placeholder="почта">
Поле обязательное для заполнения. [HTML-04](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-04).

2023-03-12 18:17 UTC, andreysgra commented on index.html
> +                name="delivery-order-form-text" placeholder="В свободной форме">
Поле обязательное для заполнения. [HTML-04](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-04).

2023-03-12 18:17 UTC, andreysgra commented on index.html
> +                name="delivery-order-form-number" value="1">
Поле обязательное для заполнения. [HTML-04](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-04).

2023-03-12 18:41 UTC, Bezlpetr commented on catalog.html
> +                    <button class="range-toggle toggle-max">
исправил

2023-03-12 18:42 UTC, Bezlpetr commented on index.html
> +        <button class="modal-close-button">
исправил

2023-03-12 18:44 UTC, Bezlpetr commented on index.html
> +                id="delivery-order-name" name="delivery-order-name" placeholder="Введите имя">
исправил

2023-03-12 18:44 UTC, Bezlpetr commented on index.html
> +                id="delivery-order-email" name="delivery-order-email" placeholder="почта">
исправил

2023-03-12 18:45 UTC, Bezlpetr commented on index.html
> +                name="delivery-order-form-text" placeholder="В свободной форме">
испарвил

2023-03-12 18:54 UTC, Bezlpetr commented on index.html
> +                name="delivery-order-form-number" value="1">
Исправил.
Как сделать состояние invalid по стайлгайду не понял.

![image](https://user-images.githubusercontent.com/33637105/224566277-ce74f392-b201-44af-b281-2edf885ac198.png)

2023-03-13 07:03 UTC, andreysgra commented on index.html
> +                name="delivery-order-form-number" value="1">
Я вижу тут только два способа реализации:
1. То, что обведено красной линией является полем `delivery-order-form-field`, а кнопки "-" и "+" располагаются поверх него.
2. Кнопки и поле ввода нужно обернуть дополнительным элементом и класс ошибки присваивать ему (класс будет добавляться с помощью JS после валидации значения в поле).

На мой взгляд дизайн здесь нелогичный, так как обводить красным цветом нужно только поле ввода.

2023-03-13 07:03 UTC, merged

2023-03-13 09:29 UTC, Bezlpetr commented on index.html
> +                name="delivery-order-form-number" value="1">
Нет времени возиться, пока не буду править.